<?php
$txt['smf3']='';
$txt['mods_cat_features'] = 'Caracter&iacute;sticas b&aacute;sicas';
$txt['allow_guestAccess'] = 'Permitir a los visitantes navegar en la web';
$txt['userLanguage'] = 'Activar Idioma seleccionado por el usuario';
$txt['allow_editDisplayName'] = '&iquest;Permitirle a los usuarios modificar su nombre?';
$txt['allow_hideOnline'] = '&iquest;Permitirle a los usuarios NO administradores ocultarse?';
$txt['allow_hideEmail'] = 'Permitirle a los usuarios esconder su email del p&uacute;blico (excepto a administradores)';
$txt['guest_hideContacts'] = 'No revelar detalles de contacto de los usuarios a los visitantes';
$txt['titlesEnable'] = 'Activar T&iacute;tulos Personalizado';
$txt['enable_buddylist'] = 'Activar Listas de Amigos';
$txt['default_personalText'] = 'Texto Personal por defecto';
$txt['max_signatureLength'] = 'N&uacute;mero m&aacute;ximo de caracteres permitido en firmas<div class="smalltext">(0 para que no haya m&aacute;x)</div>';
$txt['number_format'] = 'Formato de n&uacute;meros por defecto';
$txt['time_format'] = 'Formato de Tiempo por defecto';
$txt['time_offset'] = 'Diferencia horaria global<div class="smalltext">(agregado a las opciones espec&iacute;ficas de los usuarios.)</div>';
$txt['failed_login_threshold'] = 'Tiempo de espera al fallar un ingreso';
$txt['lastActive'] = 'Tiempo despu&eacute;s de su &uacute;ltima acci&oacute;n durante el cual los usuarios aparecer&aacute;n en l&iacute;nea';
$txt['trackStats'] = 'Rastrear Estad&iacute;sticas';
$txt['hitStats'] = 'Rastrear Hits (deben estar activadas las estad.)';
$txt['enableCompressedOutput'] = 'Activar Compresi&oacute;n de Salida';
$txt['databaseSession_enable'] = 'Usar sesiones almacenadas en la base de datos';
$txt['databaseSession_loose'] = 'Permitirle a los navegadores regresar a las p&aacute;ginas en el cache';
$txt['databaseSession_lifetime'] = 'Segundos para que expire una sesi&oacute;n no utilizada';
$txt['enableErrorLogging'] = 'Activar log de errores';
$txt['cookieTime'] = 'Duraci&oacute;n por defecto de las cookies para el ingreso (en minutos)';
$txt['localCookies'] = 'Activar el almacenamiento local de cookies<div class="smalltext">(SSI no funcionar&aacute; a&uacute;n con esto activado.)</div>';
$txt['globalCookies'] = '&iquest;Usar cookies independientes de subdominio?<div class="smalltext">&iexcl;Advertencia: Hay que deshabilitar las cookies locales primero!</div>';
$txt['securityDisable'] = '&iquest;Desactivar la seguridad en la administraci&oacute;n?';
$txt['send_validation_onChange'] = 'Enviar por email nueva contrase&ntilde;a si el usuario cambia su direcci&oacute;n de email';
$txt['approveAccountDeletion'] = 'Requerir la aprobaci&oacute;n de un administrador cuando un usuario borre su cuenta';
$txt['autoOptDatabase'] = '&iquest;Optimizar tablas cada cuantos d&iacute;as?<div class="smalltext">(0 para desactivar)</div>';
$txt['autoOptMaxOnline'] = 'M&aacute;ximos usuarios en l&iacute;nea mientras se optimiza<div class="smalltext">(0 para que no haya m&aacute;x)</div>';
$txt['autoFixDatabase'] = 'Arreglar tablas con problemas autom&aacute;ticamente';
$txt['allow_disableAnnounce'] = 'Permitir a los usuarios desactivar el recibir notificaciones de \'Foros de Anuncios\'';
$txt['disallow_sendBody'] = '&iquest;No permitir enviar el texto del mensaje en las notificaciones?';
$txt['modlog_enabled'] = 'Guardar log de las acciones de moderaci&oacute;n';
$txt['queryless_urls'] = 'Mostrar URLs sin ?s<div class="smalltext"><b>&iexcl;S&oacute;lo Apache!</b></div>';
$txt['max_image_width'] = 'Ancho m&aacute;ximo de las im&aacute;genes en los mensajes (0 = desactivar)';
$txt['max_image_height'] = 'Altura m&aacute;xima de las im&aacute;genes en los mensajes (0 = desactivar)';
$txt['mail_type'] = 'Tipo de Correo';
$txt['mail_type_default'] = '(Predeterminado de PHP)';
$txt['enableReportPM'] = 'Activar el aviso de mensajes privados';

$txt['max_pm_recipients'] = 'M&aacute;ximo n&uacute;mero de destinatarios permitidos en un mensaje privado.<div class="smalltext">(0 para ilimitado, exceptuando admins)</div>';
$txt['pm_posts_verification'] = 'Usuarios con un n&uacute;mero de mensajes por debajo del establecido, deber&aacute;n introducir un c&oacute;digo cuando envien un mensaje personal.<div class="smalltext">(0 para ilimitados, administradores est&aacute;n exentos)</div>';
$txt['pm_posts_per_hour'] = 'N&uacute;mero de mensajes personales que pueden ser enviados por un usuario en una hora.<div class="smalltext">(0 para ilimitados, moderadores est&aacute;n exentos)</div>';

$txt['mods_cat_layout'] = 'Dise&ntilde;o (Temas)';
$txt['compactTopicPagesEnable'] = 'Activar Mod de Tema Compacto';
$txt['smf235'] = 'N&uacute;mero de p&aacute;ginas contiguas a mostrar:';
$txt['smf236'] = 'para mostrar';
$txt['todayMod'] = 'Activar Mod de Hoy';
$txt['smf290'] = 'Desactivado';
$txt['smf291'] = 'S&oacute;lo Hoy';
$txt['smf292'] = 'Hoy y Ayer';
$txt['topbottomEnable'] = 'Activar botones Ir Arriba/Ir Abajo';
$txt['onlineEnable'] = 'Mostrar Conectado/Desconectado en mensajes y en MP';
$txt['enableVBStyleLogin'] = 'Activar ingreso estilo VB';
$txt['defaultMaxMembers'] = 'Usuarios por p&aacute;gina en la Lista Completa de Usuarios';
$txt['timeLoadPageEnable'] = 'Mostrar tiempo tomado para crear cada p&aacute;gina';
$txt['disableHostnameLookup'] = '&iquest;Desactivar la b&uacute;squeda de los nombres de los servidores?';
$txt['who_enabled'] = 'Activar Qui&eacute;n est&aacute; en l&iacute;nea';

?>